security:
  basic:
    enabled: true
  user:
    name: lw
    password: lw
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://lw:lw@localhost:8761/eureka
